import type { FeedGroup } from '../app/types/feed'
// 友链检测 CLI 需要使用显式导入和相对路径
import { myFeed } from '../blog.config'
// eslint-disable-next-line unused-imports/no-unused-imports
import { getFavicon, getGithubAvatar, getGithubIcon, getOciqGroupAvatar, getOicqAvatar, OicqAvatarSize } from './utils/img'

export default [
	// #region Clarity
	{
		name: '清晰体验',
		desc: '使用 Clarity 博客主题构建的网站。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			myFeed,
			{
				author: 'GuuGuai',
				sitenick: '杂记本',
				title: '古怪杂记本',
				desc: '一个什么都可能会写的博客',
				link: 'https://blog.guuguai.site/',
				feed: 'https://blog.guuguai.site/atom.xml',
				icon: 'https://cravatar.cn/avatar/646331BFF8F19A0E05679C3CC0FC54D6',
				avatar: 'https://cdn.libravatar.org/avatar/646331bff8f19a0e05679c3cc0fc54d6?s=160',
				archs: ['Nuxt', 'Netlify'],
				date: '2023-12-23',
				comment: '高中同学，技术好友，爱好番剧/折腾。',
			},
			{
				author: '小李同学',
				sitenick: 'Coding',
				title: '小李同学 Coding',
				desc: '一支努力变强的小彩笔',
				link: 'https://blog.junjieli.top/',
				feed: 'https://blog.junjieli.top/atom.xml',
				icon: 'https://blog.junjieli.top/api/icon.webp',
				avatar: 'https://www.junjieli.top/logo_64x64.png',
				archs: ['Nuxt', 'Vercel'],
				date: '2024-02-01',
				comment: '瓜大网安学长。',
			},
			{
				author: 'Xlenco',
				sitenick: '希乐博客',
				desc: '互联网中的静谧之地',
				link: 'https://blog.xlenco.top/',
				feed: 'https://blog.xlenco.top/atom.xml',
				icon: 'https://weavatar.com/avatar/67254b346498965226e5c91ebff66a69570b97f224d2d061e504b4eade1f00fa',
				avatar: getOicqAvatar('1043865083'),
				archs: ['Nuxt', 'EdgeOne'],
				date: '2024-07-28',
				comment: '学生，经验分享。',
			},
			{
				author: '梦爱吃鱼',
				desc: '不负心灵，不负今生。',
				link: 'https://blog.bsgun.cn/',
				feed: 'https://blog.bsgun.cn/atom.xml',
				icon: 'https://www.bsgun.cn/favicon.ico',
				avatar: 'https://oss-cdn.bsgun.cn/logo/avatar.256.png',
				archs: ['Nuxt', 'EdgeOne'],
				date: '2024-08-20',
				comment: '博客折腾',
			},
			{
				author: '鹊楠',
				sitenick: '小窝',
				title: '鹊楠の小窝',
				desc: '世界那么大，我想去看看',
				link: 'https://blog.quenan.cn/',
				feed: 'https://blog.quenan.cn/atom.xml',
				icon: 'https://pic1.imgdb.cn/item/6900c4b13203f7be00ac9ded.png',
				avatar: 'https://pic1.imgdb.cn/item/69d51522cfae5fcb267af121.webp',
				archs: ['Nuxt', 'Vercel'],
				date: '2024-10-22',
				comment: '学生，技术分享。',
			},
			{
				author: '唤青',
				sitenick: 'Abloom',
				title: '唤青映记',
				desc: 'Per aspera ad astra',
				link: 'https://blog.abloom.site/',
				feed: 'https://blog.abloom.site/atom.xml',
				icon: getGithubIcon('abloom25'),
				avatar: getGithubAvatar('abloom25'),
				archs: ['Nuxt', 'Cloudflare'],
				date: '2024-12-09',
				comment: '高中生，技术学习中，因AI发展太快差点学会前端。',
			},
			{
				author: 'Mugzx',
				title: 'Mugzx\'s Blog',
				desc: '向上革命，向下实践。',
				link: 'https://blog.mugzx.top/',
				feed: 'https://blog.mugzx.top/atom.xml',
				icon: 'https://www.mugzx.top/api/icon.png',
				avatar: 'https://www.mugzx.top/api/avatar.png',
				archs: ['Nuxt', 'Vercel'],
				date: '2025-01-29',
				comment: '思考博客与技术观建设。',
			},
			{
				author: 'Mikuの鬆',
				sitenick: '极光星',
				title: 'Mikuの极光星',
				desc: '心有多宽，世界就有多远',
				link: 'https://blog.sotkg.com/',
				feed: 'https://blog.sotkg.com/atom.xml',
				icon: 'https://cn.cravatar.com/avatar/1012bf78fb01d5b964c3a9a0f515911a.png',
				avatar: 'https://cn.cravatar.com/avatar/1012bf78fb01d5b964c3a9a0f515911a.png',
				archs: ['Nuxt', 'EdgeOne'],
				date: '2025-03-22',
				comment: '动漫文化与自部署技术的碰撞。',
			},
			{
				author: '东方月初',
				sitenick: 'BiuXin',
				title: 'BiuXin-s Blog',
				desc: '人生的每一天，都在学习当中',
				link: 'https://blog.biuxin.de/',
				feed: 'https://blog.biuxin.de/atom.xml',
				icon: 'https://x.xinb.de/i/2024/09/19/040857.webp',
				avatar: getGithubAvatar('damizai'),
				archs: ['Nuxt', 'Cloudflare'],
				date: '2025-05-09',
				comment: '软件工具资源，博客部署美化。',
			},
			{
				author: 'Shenley',
				sitenick: '存档点',
				title: 'Shenley的存档点',
				desc: '随手存个档～',
				link: 'https://blog.shenley.cn/',
				feed: 'https://blog.shenley.cn/atom.xml',
				icon: 'https://blog.shenley.cn/avatar.jpg',
				avatar: 'https://blog.shenley.cn/avatar.jpg',
				archs: ['Nuxt', 'Vercel'],
				date: '2025-05-20',
				comment: '前端开发、生活分享。',
			},
			{
				author: '液泡',
				sitenick: '部落格',
				title: '液泡部落格',
				desc: '一介书生，三尺微命',
				link: 'https://blog.vacu.top/',
				feed: 'https://blog.vacu.top/atom.xml',
				icon: 'https://blog.vacu.top/favicon.ico',
				avatar: 'https://blog.vacu.top/assets/img/avatar.png',
				archs: ['Nuxt', 'Cloudflare'],
				date: '2025-07-26',
				comment: '对世界的学习与思考。',
			},
			{
				author: '月空人',
				desc: '偶尔写些博客，发发牢骚',
				link: 'https://www.weilog.me/',
				feed: 'https://www.weilog.me/atom.xml',
				icon: 'https://www.weilog.me/favicon.ico',
				avatar: 'https://bitmc.uno/picgo/126662463_p2.jpg',
				archs: ['Nuxt', 'Vercel'],
				date: '2025-07-28',
				comment: '前端大手子，运营prop.show播客，分享前端技术的心得。',
			},
			{
				author: '落憾',
				sitenick: 'EnLtLH',
				title: '落憾',
				desc: '建此博客，以示吾思。话天篆地，自由吾心。',
				link: 'https://blog.luoh.org/',
				feed: 'https://blog.luoh.org/atom.xml',
				icon: 'https://cdn2.elh.dpdns.org/picture/2025/5223b2101b56608abd83b63642984b1f.avif',
				avatar: 'https://cdn2.elh.dpdns.org/picture/2025/57bd486ead4f5b34a28aea7f160a70ae.avif',
				archs: ['Nuxt', 'Vercel'],
				date: '2025-08-17',
				comment: '中学生，以诗词、杂记等形式记录感悟与创作。',
			},
			{
				author: 'AirTouch',
				desc: '分享技术、生活、思考。',
				link: 'https://www.xsl.im/',
				feed: 'https://www.xsl.im/atom.xml',
				icon: 'https://www.xsl.im/favicon.webp',
				avatar: 'https://www.xsl.im/avatar.webp',
				archs: ['Nuxt', '服务器'],
				date: '2025-08-18',
				comment: '网站反代配置、服务器评测、域名更换、存储加速、工具推荐、编程题解等折腾与技术分享。',
			},
			{
				author: '筱序二十',
				sitenick: '青序栈',
				desc: '青序成栈·向简而生',
				link: 'https://www.qixz.cn/',
				feed: 'https://www.qixz.cn/feed/',
				icon: 'https://www.qixz.cn/favicon.svg',
				avatar: 'https://www.qixz.cn/avatar.avif',
				archs: ['Nuxt', '国内 CDN'],
				date: '2025-08-20',
				comment: '网站攻击处理曝光，博客配置魔改等技术教程与资源分享。',
			},
			{
				author: '落尘up',
				desc: '愿你我都做,生活的高手。',
				link: 'https://www.luochen.chat/',
				feed: 'https://www.luochen.chat/atom.xml',
				icon: 'https://www.luochenup.xyz/b_a5a3aa888355bdc617dca021efb19ab8.png',
				avatar: 'https://www.luochenup.xyz/b_a5a3aa888355bdc617dca021efb19ab8.png',
				archs: ['Nuxt', 'Vercel'],
				date: '2025-08-28',
				comment: '前端与技术入门。',
			},
			{
				author: '克喵',
				sitenick: '喵落阁',
				title: '喵落阁',
				desc: '愿你看清一切真相后，依旧热爱你的家人和朋友。',
				link: 'https://blog-v3.kemeow.top/',
				feed: 'https://blog-v3.kemeow.top/atom.xml',
				icon: 'https://img.314926.xyz/images/2025/08/13/no-background-kemiaofxjun.webp',
				avatar: 'https://img.314926.xyz/images/2025/08/13/no-background-kemiaofxjun.webp',
				archs: ['Nuxt', 'Vercel'],
				date: '2025-09-11',
				comment: '博客折腾记录、工具/资源网站收集。',
			},
			{
				author: 'fishcpy',
				sitenick: '小破站',
				title: 'fishcpy的小破站',
				desc: '非淡泊无以明志，非宁静无以致远',
				link: 'https://blog.fis.ink/',
				feed: 'https://blog.fis.ink/atom.xml',
				icon: 'https://www.fis.ink/img/logo_c.png',
				avatar: 'https://www.fis.ink/img/logo.png',
				archs: ['Nuxt', 'EdgeOne'],
				date: '2025-09-13',
				comment: '博客/服务器技术实践、生活记录、资源分享。',
			},
			{
				author: 'Cталин',
				desc: '未觉池塘春草梦，阶前梧叶已秋声',
				link: 'https://blog.jiclub.site/',
				feed: 'https://blog.jiclub.site/atom.xml',
				icon: 'https://m4.publicimg.browser.qq.com/publicimg/nav/qbtool/qbtool-latest.png',
				avatar: getOicqAvatar('1545433540'),
				archs: ['Nuxt', 'EdgeOne'],
				date: '2025-10-12',
				comment: '情绪记录与表达。',
			},
			{
				author: '栖童',
				title: '栖童の小站',
				desc: '越努力,越幸运',
				link: 'https://blog.linux-qitong.top/',
				feed: 'https://blog.linux-qitong.top/atom.xml',
				icon: 'https://blog.linux-qitong.top/img/favicon.webp',
				avatar: 'https://blog.linux-qitong.top/img/avatar.webp',
				archs: ['Nuxt', 'Vercel'],
				date: '2025-10-17',
				comment: '原名青稚，博客记录Linux使用、博客部署、生活反思。',
			},
			{
				author: '灯火不休时',
				desc: '所爱隔山海，山海不可平；所念皆星河，星河不可及',
				link: 'https://blog.dhbxs.top/',
				feed: 'https://blog.dhbxs.top/feed.xml',
				icon: 'https://file.dhbxs.top/2026/01/nllahmfi.png',
				avatar: 'https://file.dhbxs.top/ylvwvjjs.jpg',
				archs: ['Halo', '国内 CDN'],
				date: '2025-11-01',
				comment: '深度学习、大数据与软件工程学习笔记。',
			},
			{
				author: '墨韵云阁',
				desc: '记录零散思路与技术点滴，在代码与日常间缓慢积累。偶作深思，闲时随笔，只为给此刻留下一点痕迹🪵',
				link: 'https://luoyuanxiang.top/',
				feed: 'https://luoyuanxiang.top/atom.xml',
				icon: 'https://cdn.luoyuanxiang.top/moyunyunge-logo.png',
				avatar: 'https://cdn.luoyuanxiang.top/avatar.png',
				archs: ['Nuxt', 'Vercel'],
				date: '2025-11-04',
				comment: '后端与运维笔记。',
			},
			{
				author: 'Lyi.',
				title: '凌梦望初晓',
				desc: '在无尽的绝望中前行...',
				link: 'https://blog.lyi.moe/',
				feed: 'https://blog.lyi.moe/atom.xml',
				icon: 'https://i.lyi.moe/avatar',
				avatar: 'https://i.lyi.moe/avatar',
				archs: ['Nuxt', 'Cloudflare'],
				date: '2025-12-15',
				comment: '专升本课程复习笔记。',
			},
			{
				author: '敖苛记',
				desc: '敖致天，苛制人',
				link: 'https://blog.kayro.cn/',
				feed: 'https://blog.kayro.cn/atom.xml',
				icon: 'https://blog.kayro.cn/favicon.svg',
				avatar: 'https://blog.kayro.cn/avatar.webp',
				archs: ['Nuxt', 'EdgeOne'],
				date: '2026-05-11',
				comment: '分享系统搭建、工具配置、AI 部署及编程学习笔记的技术博客。',
			},
		],
	},
	// #endregion
	// #region 网上邻居 since 2024
	{
		name: '网上邻居',
		desc: '哔——啵——电波通讯中，欢迎常来串门。',
		// @keep-sorted { "keys": ["date"] }
		entries: [
			{
				author: 'isYangs',
				desc: '一个前端Bug构造师的博客',
				link: 'https://www.isyangs.cn/',
				feed: 'https://www.isyangs.cn/feed.xml',
				icon: 'https://www.isyangs.cn/favicon.svg',
				avatar: 'https://7.isyangs.cn/8/655c9835780a0-8.jpg',
				archs: ['Vue', '国内 CDN'],
				date: '2024-01-29',
				comment: '默认',
			},
			/* ========从此处新增友链======== */
		],
	},
] satisfies FeedGroup[]
